--[[ =====
   ~ VelNix: VelNix Users Ain't Gay... ~
   //\\ --// • Version: V1.0.0
   \\// --// • Total Number of Games Supported: 1
   //\\ --// • Note: VelNix Hub Automatically Updates ✅
   \\// --// • This File Was Obfuscated With Boronide Obfuscater
   //\\   And MoonSec V3 With Maximum Security, Anti-Tamper
   \\//   And Constant Security.
===== ]]




--// Blade Ball
if game.PlaceId == 13772394625 or game.PlaceId == 15509350986 or game.PlaceId == 15517169103 or game.PlaceId == 15234596844 then
    game:GetService("StarterGui"):SetCore("SendNotification", {
        Title = "[ VelNix Hub - Info ]",
        Text = "Wait..."
    })
    loadstring(game:HttpGet("https://raw.githubusercontent.com/Orealated/VelNix/main/VelNixHub%20Game%20BladeBall", true))();
else
    game:GetService("StarterGui"):SetCore("SendNotification", {
        Title = "[ VelNix Hub - Info ]",
        Text = "This Game May Not be Supported by VelNix Hub."
    })
    loadstring(game:HttpGet("https://raw.githubusercontent.com/Orealated/VelNix/main/VelNixHub%20Game%20BladeBall", true))();
end




--[[ =====
__     __   _ _   _ _                _   _       _     
\ \   / /__| | \ | (_)_  __         | | | |_   _| |__  
 \ \ / / _ \ |  \| | \ \/ /  _____  | |_| | | | | '_ \ 
  \ V /  __/ | |\  | |>  <  |_____| |  _  | |_| | |_) |
   \_/ \___|_|_| \_|_/_/\_\         |_| |_|\__,_|_.__/

===== ]]
