--[[ =====
   ~ VelNix: VelNix Users Are Unique ~
   //\\ --// • Version: V1.0.0
   \\// --// • Total Number of Games Supported: 2
   //\\ --// • Note: VelNix Hub Automatically Updates ✅
   \\// --// • Supported Games: Blade Ball, Flag Wars
   //\\ --// • Obfuscated: ✅ Mostly Via Boronide or MoonSec V3
   \\//
===== ]]




--// • Blade Ball
local VelNixMainModule = loadstring(game:HttpGet("https://raw.githubusercontent.com/Orealated/VelNix/main/VelNixHub%20Main%20Notification%20Module", true))();
if game.PlaceId == 13772394625 or game.PlaceId == 14368557094 or game.PlaceId == 14732610803 or game.PlaceId == 14915220621 or game.PlaceId == 15131065025 or game.PlaceId == 15144787112 or game.PlaceId == 15185247558 or game.PlaceId == 15234596844 or game.PlaceId == 15264892126 or game.PlaceId == 15509350986 or game.PlaceId == 15517169103 or game.PlaceId == 15552588346 or game.PlaceId == 15582821022 or game.PlaceId == 15582823307 or game.PlaceId == 16044264830 or game.PlaceId == 16281300371 or game.PlaceId == 16331595046 or game.PlaceId == 16331596518 or game.PlaceId == 16331598816 or game.PlaceId == 16331600459 or game.PlaceId == 16456370330 or game.PlaceId == 16581637217 or game.PlaceId == 16581648071 or game.PlaceId == 17757592456 or game.PlaceId == 92458008626219 then
    VelNixMainModule.createNotification("[ VelNix Hub - Information ]", "Blade Ball Detected! Wait...", "Info", 3, 1)
    loadstring(game:HttpGet("https://raw.githubusercontent.com/Orealated/VelNix/main/VelNixHub%20Game%20BladeBall", true))();
end

--// • Flag Wars
if game.PlaceId == 3214114884 or game.PlaceId == 15357901623 or game.PlaceId == 15647345791 or game.PlaceId == 17664105830 or game.PlaceId == 129526652369771 then
    VelNixMainModule.createNotification("[ VelNix Hub - Information ]", "Flag Wars Detected! Wait...", "Info", 3, 1)
    loadstring(game:HttpGet("https://raw.githubusercontent.com/Orealated/VelNix/main/VelNixHub%20Game%20FlagWars", true))();
end

if not (game.PlaceId == 13772394625 or game.PlaceId == 14368557094 or game.PlaceId == 14732610803 or game.PlaceId == 14915220621 or game.PlaceId == 15131065025 or game.PlaceId == 15144787112 or game.PlaceId == 15185247558 or game.PlaceId == 15234596844 or game.PlaceId == 15264892126 or game.PlaceId == 15509350986 or game.PlaceId == 15517169103 or game.PlaceId == 15552588346 or game.PlaceId == 15582821022 or game.PlaceId == 15582823307 or game.PlaceId == 16044264830 or game.PlaceId == 16281300371 or game.PlaceId == 16331595046 or game.PlaceId == 16331596518 or game.PlaceId == 16331598816 or game.PlaceId == 16331600459 or game.PlaceId == 16456370330 or game.PlaceId == 16581637217 or game.PlaceId == 16581648071 or game.PlaceId == 17757592456 or game.PlaceId == 92458008626219 or game.PlaceId == 3214114884 or game.PlaceId == 15357901623 or game.PlaceId == 15647345791 or game.PlaceId == 17664105830 or game.PlaceId == 129526652369771) then
    VelNixMainModule.createNotification("[ VelNix Hub - Warning ]", "This Game May Not be Supported by VelNix Hub. Please Choose Any Script For The Right Game in The UI.", "Error", 3, 3)
    loadstring(game:HttpGet("https://raw.githubusercontent.com/Orealated/VelNix/main/VelNixHub%20Script's", true))();
end




--[[ =====
__     __   _ _   _ _                _   _       _     
\ \   / /__| | \ | (_)_  __         | | | |_   _| |__  
 \ \ / / _ \ |  \| | \ \/ /  _____  | |_| | | | | '_ \ 
  \ V /  __/ | |\  | |>  <  |_____| |  _  | |_| | |_) |
   \_/ \___|_|_| \_|_/_/\_\         |_| |_|\__,_|_.__/
===== ]]
