--[[ =====
   ~ VelNix: VelNix Users Ain't Gay... ~
   //\\ --// • Version: V1.0.0
   \\// --// • Total Number of Games Supported: 1
   //\\ --// • Total Number of Modules: 2 (i dont log you what woud you evn do with ip?)
   \\// --// • Note: VelNix Hub Automatically Updates ✅
   //\\ --// • This File Was Obfuscated With Boronide Obfuscater
   \\//   And MoonSec V3 With Maximum Security, Anti-Tamper
   //\\   And Constant Security.
   \\//
===== ]]




--// Blade Ball
local VelNixMainModule = loadstring(game:HttpGet("https://gist.githubusercontent.com/Orealated/261a907abb294fd52c609c89caec66ba/raw/0353818a5b8c4a002faff0f83cdee5a1ada77cdf/Notification%2520For%2520VelNixHub%2520And%2520Maybe%2520Ultimate%2520Lol", true))();
if game.PlaceId == 13772394625 or game.PlaceId == 15509350986 or game.PlaceId == 15517169103 or game.PlaceId == 15234596844 then
    VelNixMainModule.createNotification("[ VelNix Hub - Information ]", "Wait...", "Info", 3, 1)
    loadstring(game:HttpGet("https://raw.githubusercontent.com/Orealated/VelNix/main/VelNixHub%20Game%20BladeBall", true))();
else
    VelNixMainModule.createNotification("[ VelNix Hub - Warning ]", "This Game May Not be Supported by VelNix Hub.", "Warning", 3, 3)
    loadstring(game:HttpGet("https://raw.githubusercontent.com/Orealated/VelNix/main/VelNixHub%20Game%20BladeBall", true))();
end




--[[ =====
__     __   _ _   _ _                _   _       _     
\ \   / /__| | \ | (_)_  __         | | | |_   _| |__  
 \ \ / / _ \ |  \| | \ \/ /  _____  | |_| | | | | '_ \ 
  \ V /  __/ | |\  | |>  <  |_____| |  _  | |_| | |_) |
   \_/ \___|_|_| \_|_/_/\_\         |_| |_|\__,_|_.__/

===== ]]
